@echo off
cd /d "%~dp0"
echo Starting YouTube Downloader - MP3 ^& MP4...
echo Refreshing environment variables...
call refreshenv 2>nul || echo Note: refreshenv not available, continuing anyway...
.venv\Scripts\python.exe YouToMp3.py
pause
